### Works.
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Wayan",
    "number": "0331-1234567"
}

### Error; missing content.
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "092-1234567"
}

### Error; duplicate number.
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Rango Tamarind",
    "number": "12-43-234345"
}